juju add-relation prometheus:grafana-source grafana:grafana-source
juju add-relation telegraf:prometheus-client prometheus:target
juju add-relation kubernetes-control-plane:juju-info telegraf:juju-info
juju add-relation kubernetes-control-plane:prometheus prometheus:manual-jobs
juju add-relation kubernetes-control-plane:grafana grafana:dashboards
juju add-relation prometheus:certificates easyrsa:client
juju add-relation kubernetes-worker:juju-info telegraf:juju-info
juju add-relation kubernetes-worker:scrape prometheus:scrape
juju add-relation etcd:grafana grafana:dashboards
juju add-relation etcd:prometheus prometheus:manual-jobs